version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # 사용할 Java 버전
    commands:
      - echo Installing dependencies...

  pre_build:
    commands:
      - echo Pre-build started...

  build:
    commands:
      - echo Build started...
      - ./gradlew clean build -x test  # Gradle을 사용한 빌드 명령어

  post_build:
    commands:
      - echo Build completed successfully
      - echo Starting post-build...

artifacts:
  files:
    - appspec.yml  # CodeDeploy를 위한 appspec 파일
    - build/libs/*.jar  # 빌드된 JAR 파일
    - scripts/**  # 추가한 스크립트들

cache:
  paths:
    - ~/.gradle/caches/**  # Gradle 캐시를 사용하여 빌드 시간 단축
    - ~/.gradle/wrapper/**

