name: CI/CD using Github Actions & AWS CodeDeploy

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            

      - name: make application.yml

        if: contains(github.ref, 'develop')
        run: |
            mkdir -p ./src/main/resources
            cd ./src/main/resources
            touch ./application.yml
            echo "${{ secrets.YML }}" >
        shell: bash


      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials for S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp ./$GITHUB_SHA.zip s3://studybadgebucket/deploy/$GITHUB_SHA.zip

      - name: Configure AWS credentials for CodeDeploy
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Code Deploy
        run: |
          aws deploy create-deployment \
            --application-name studybadge \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name studybadge-deploy \
            --s3-location bucket=studybadgebucket,bundleType=zip,key=deploy/$GITHUB_SHA.zip
